config/routes.rb
Rails.application.routes.draw do

  get 'cardapios/new'

  get 'cardapios/index'

  get 'cardapios/edit'

  get 'restaurantes/index'
  post 'restaurantes/create'
  patch 'restaurantes/update'
  post 'restaurantes/update'
  get 'restaurantes/delete'
  get 'restaurantes/confirm'
  get 'restaurantes/data'
  get  'restaurantes/layout_central'
  get 'restaurantes/layout_fisica'
  get 'restaurantes/img_reserva'

  get 'dado_inseridos/delete'
  get 'dado_inseridos/create_url'
  get 'sessions/new'

  get 'estima_fila/update'


  root 'static_pages#home'
  get  '/help',    to: 'static_pages#help'
  get  '/about',   to: 'static_pages#about'
  get  '/contact', to: 'static_pages#contact'

  get 'static_pages/novo_restaurante'

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  get 'sessions/new'

  get 'pagina_admin/admin'
  get 'admins/index'
  post 'admins/create'
  post 'admins/createCookie'
  post 'admins/createWCookies'
  patch 'admins/update'
  get 'admins/delete'
  post 'admins/update'
  post "admins/delete_multiple"
  post "admins/select_multiple"

  get 'cardapios/index'
  patch 'cardapios/edit'
  post 'cardapios/edit'
  patch 'cardapios/update'


  resources :dado_inseridos
  resources :filas
  resources :restaurantes
  resources :admins
  resources :admins, :collection => {:delete_multiple => :post}
  resources :cardapios

  root 'application#hello'
end

app/models/restaurante.rb
class Restaurante < ApplicationRecord
	validates :nome, presence: true
	validates :nome, uniqueness: true


	validates :layout, presence: true
	
	
	validates :mapa, presence: true
	validates :mapa, uniqueness: true
	
	validates :foto, presence: true
	validates :foto, uniqueness: true
end

app/controllers/restaurantes_controller.rb
class RestaurantesController < ApplicationController
  before_action :set_restaurante, only: [:show, :edit, :update, :destroy]

  # GET /restaurantes
  # GET /restaurantes.json
  def index
    @restaurantes = Restaurante.all
  end

  # GET /restaurantes/1
  # GET /restaurantes/1.json
  def show
  end

  # GET /restaurantes/new
  def new
    @restaurante = Restaurante.new
  end

  # GET /restaurantes/1/edit
  def edit
  end

  # POST /restaurantes
  # POST /restaurantes.json
  def create
    @restaurante = Restaurante.new(restaurante_params)
    id = 0
    while Fila.find_by(id: id)
      id = id +1
    end
    Fila.new(id: id, estado_fila: 0, id_restaurante: @restaurante.id).save
    respond_to do |format|
      if @restaurante.save
        format.html { redirect_to @restaurante, notice: 'Restaurante foi criado com sucesso' }
        format.json { render :show, status: :created, location: @restaurante }
      else
        format.html { render :new }
        format.json { render json: @restaurante.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /restaurantes/1
  # PATCH/PUT /restaurantes/1.json
  def update
    respond_to do |format|
      if @restaurante.update(restaurante_params)
        format.html { redirect_to @restaurante, notice: 'Restaurante foi editado com sucesso' }
        format.json { render :show, status: :ok, location: @restaurante }
      else
        format.html { render :edit }
        format.json { render json: @restaurante.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /restaurantes/1
  # DELETE /restaurantes/1.json
  def destroy
    @restaurante.destroy
    respond_to do |format|
      format.html { redirect_to restaurantes_url, notice: 'Restaurante foi deletado com sucesso' }
      format.json { head :no_content }
    end
  end

  def delete
    Restaurante.find(params[:id]).destroy
    redirect_to :action => 'index'
  end

  def layout_central
  end
  def layout_fisica
  end
  def img_reserva
  end

  

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_restaurante
      @restaurante = Restaurante.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def restaurante_params
      params.require(:restaurante).permit(:nome, :cardapio, :layout, :mapa, :foto)
    end
end

app/helpers/restaurantes_helper.rb
module RestaurantesHelper
end

app/views/restaurantes/_form.html.erb
<% if  logged_in? %>

<%= form_with(model: restaurante, local: true) do |form| %>
  <% if restaurante.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(restaurante.errors.count, "error") %> prohibited this restaurante from being saved:</h2>

      <ul>
      <% restaurante.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <h3 style="text-align:center;">Por favor, fornecer as informações pedidas abaixo</h3>

       <head>
    <style>
    div {
    font-family: arial, sans-serif;
    border-collapse: collapse;
    width: 100%;
    }

    div {
    text-align: center;
    padding: 4px;
    }

    div:nth-child(even) {

    }
    </style>
    </head>


  <div class="field">
    <%= form.label :nome %>
    <%= form.text_field :nome, id: :restaurante_nome %>
  </div>

  <div class="field">
    <%= form.label :cardápio %>
    <%= form.text_field :cardapio, id: :restaurante_cardapio %>
  </div>

  <div class="field">
    <%= form.label :layout %>
    <%= form.text_field :layout, id: :restaurante_layout %>
  </div>

  <div class="field">
    <%= form.label :mapa %>
    <%= form.text_field :mapa, id: :restaurante_mapa %>
  </div>

  <div class="field">
    <%= form.label :foto %>
    <%= form.text_field :foto, id: :restaurante_foto %>
  </div>

  <div class="actions">
    <%= form.submit 'Concluir' %>
  </div>
<% end %>

<% else %>
<h1>Não logado </h1>
<meta http-equiv="refresh" content="0; url=/" /> 

<% end %> 

app/views/restaurantes/edit.html.erb
<% if  logged_in? %>

<head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                                              'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <%= yield %>
    </div>
</body>


<style>
input[type=text], select {
    text-align: center;
    width: 50%;
    padding: 6px 10px;
    margin: 1px 0;
    border: 1px solid #ccc;
    border-radius: 4px;

}

input[type=submit] {
    width: 10%;
    background-color: rgb(34, 34, 34);
    color: white;
    padding: 6px 10px;
    margin: 8px 0;
    border: none;
    border-radius: 4px;
    cursor: pointer;
}

div {
    border-radius: 5px;
    padding: 20px;
}
</style>

<h1 style="text-align:center;">Editando Restaurante</h1>

<%= render 'form', restaurante: @restaurante %>

<p style="text-align:center;"><%= link_to 'Mostrar', @restaurante %></p> 
<p style="text-align:center;"><%= link_to 'Voltar', restaurantes_path %></p>

 <div class="container">
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>

<% else %>
<h1>Não logado </h1>
<meta http-equiv="refresh" content="0; url=/" /> 

<% end %> 

app/views/restaurantes/img_reserva.erb
<!DOCTYPE html>
<html>
<body>
<img src="/assets/img_reserva.jpg"/>


</body>
</html>

app/views/restaurantes/index.html.erb
<!DOCTYPE html>

<% if  logged_in? %>
<head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                                              'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <%= yield %>
    </div>
</body>


<head>
<style>
{
    font-family: "Trebuchet MS", Arial, Helvetica, sans-serif;
    border-collapse: collapse;
    width: 100%;
}

td, th {
    padding: 8px;
    border-bottom: 1px solid #ddd;
}

tr:nth-child(even){background-color: #f2f2f2;}

tr:hover {background-color: #ddd;}

th {
    padding-top: 12px;
    padding-bottom: 12px;
    text-align: left;
    background-color: rgb(34, 34, 34);
    color: white;
}

</style>
</head>

<p id="notice"><%= notice %></p>

<h1 style="text-align:center;">Restaurantes</h1>

<body>
<table style="width:100%">
  <thead>
    <tr>
      <th>Nome</th>
      
      <th>Mapa</th>
      <th>Foto</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @restaurantes.each do |restaurante| %>
      <tr>
        <td><%= restaurante.nome %></td>
        
        <td><%= link_to 'Mapa/Layout', restaurante, :target => "_blank" %></td>
        <td><img src=<%=restaurante.foto %> width="149" height="105" /img></td>
        <td><%= link_to 'Editar', edit_restaurante_path(restaurante) %></td>
        <td><%= link_to 'Apagar restaurante', {:action => 'delete', :id => restaurante.id}, data: { confirm: "Você tem certeza?" } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</body>
<br>

<p style="text-align:center;"><%= link_to 'Novo Restaurante', new_restaurante_path %></p>

 <div class="container">
      <%= yield %>
      <%= render 'layouts/footer' %>
 </div>

<% else %>
<h1>Não logado </h1>
<meta http-equiv="refresh" content="0; url=/" /> 

<% end %> 

app/views/restaurantes/new.html.erb
<% if  logged_in? %>

<head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                                              'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <%= yield %>
    </div>
</body>

<style>
input[type=text], select {
    text-align: center;
    width: 50%;
    padding: 6px 10px;
    margin: 1px 0;
    border: 1px solid #ccc;
    border-radius: 4px;

}

input[type=submit] {
    width: 10%;
    background-color: rgb(34, 34, 34);
    color: white;
    padding: 6px 10px;
    margin: 8px 0;
    border: none;
    border-radius: 4px;
    cursor: pointer;
}

div {
    border-radius: 5px;
    background-color: ;
    padding: 20px;
}
</style>


<h1 style="text-align:center;">Inserir novo restaurante</h1>

<%= render 'form', restaurante: @restaurante %>

<p style="text-align:center;"><%= link_to 'Voltar', restaurantes_path %></p>

 <div class="container">
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>

<% else %>
<h1>Não logado </h1>
<meta http-equiv="refresh" content="0; url=/" /> 

<% end %> 

app/views/restaurantes/show.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                                              'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <%= yield %>
    </div>
    <div class="center jumbotron">



<h3 style="text-align:center;">Informações do restaurante</h3><br>

   
<p style="text-align:center;">
  <strong><%= @restaurante.nome %></strong>
</p><br>



 

<p style="text-align:center;">
  <strong>Mapa:</strong><br><br>
  <img id= "layout" src=<%= @restaurante.mapa %> width="900" height="600" usemap= <%= "#" + @restaurante.nome + "mapa"%>>
</p>
<map name= <%= @restaurante.nome + "mapa" %>>

<% @restaurante.layout.split("|").each do |g| %>
<% i = 0%>
  <% g.split(";").each do |f| %>
    <area shape="rect" coords=<%= f %> alt = <%= i.to_s%>   href= <%= "/dado_inseridos/" + "create_url?id_restaurante=" + Fila.find_by(id_restaurante: @restaurante.id).id.to_s + "&posicao=" + i.to_s %>>
    <% i = i +1 %>
<%end%>
<% i = 0 %>
<%end%>
</map>

<p><strong>Cardápio do dia:</strong> 
      
      <% Cardapio.all.each do |f|%>
        <% if (f.dia_semana == Date.current.strftime('%A') ) and (f.id_restaurante == @restaurante.id) %>
          <%f.conteudo.split("#").each do |g| %>
            <li><%= g %> </li>
          <% end %>
        <% end %>
      <% end %>
</p>

<script>
window.onload = function() {
    var c = document.getElementById("myCanvas");
    var ctx = c.getContext("2d");
    var img = document.getElementById("layout");
    ctx.drawImage(img, 0, 0);
    
    <% if Fila.find_by(id_restaurante: @restaurante.id).estado_fila > 0 %>
      ctx.fillStyle = '#f00';
      <%@restaurante.layout.split("|").each do |g|%>
        <% i = 0 %>
        //vezes que isso foi rodado
        <%g.split(";").each do |f|%>
          <% x = f.split(",") %>
          <% if i < Fila.find_by(id_restaurante: @restaurante.id).estado_fila + 1 %>
            

            <% xscale = 1 %>
            <% yscale = 1 %>
            ctx.beginPath();
            ctx.moveTo(<%= x[0].to_i*xscale %>, <%=x[1].to_i*yscale %> );
            ctx.lineTo(<%= x[2].to_i*xscale %>, <%=x[1].to_i*yscale %> );
            ctx.lineTo(<%= x[2].to_i*xscale %>, <%=x[3].to_i*yscale %> );
            ctx.lineTo(<%= x[0].to_i*xscale %>, <%=x[3].to_i*yscale %> );
            ctx.lineTo(<%= x[0].to_i*xscale %>, <%=x[1].to_i*yscale %> );
            ctx.closePath();
            ctx.fill();
            <% i = i + 1 %>
          <% end  %> 
        <% end %> 
      <% end %>
    <% end %> 

    var image = document.getElementById("layout");
    
    image.src = c.toDataURL();
   // document.body.appendChild(image);
    console.log(c.toDataURL());
    c.style.visibility = "hidden";
 

    

}
</script>


<p style="text-align:center;">
  <strong>Foto:</strong><br><br>
  <img src=<%= @restaurante.foto %> width="149" height="105" /img>
</p>

<p style="text-align:center;"><%= link_to 'Voltar', "/#" %></p>



 

<div class="container">
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>



  </body>

<canvas id = "myCanvas" width="900" height="600"></canvas>

</html>