config/routes.rb
Rails.application.routes.draw do

  get 'cardapios/new'

  get 'cardapios/index'

  get 'cardapios/edit'

  get 'restaurantes/index'
  post 'restaurantes/create'
  patch 'restaurantes/update'
  post 'restaurantes/update'
  get 'restaurantes/delete'
  get 'restaurantes/confirm'
  get 'restaurantes/data'
  get  'restaurantes/layout_central'
  get 'restaurantes/layout_fisica'
  get 'restaurantes/img_reserva'

  get 'dado_inseridos/delete'
  get 'dado_inseridos/create_url'
  get 'sessions/new'

  get 'estima_fila/update'


  root 'static_pages#home'
  get  '/help',    to: 'static_pages#help'
  get  '/about',   to: 'static_pages#about'
  get  '/contact', to: 'static_pages#contact'

  get 'static_pages/novo_restaurante'

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  get 'sessions/new'

  get 'pagina_admin/admin'
  get 'admins/index'
  post 'admins/create'
  post 'admins/createCookie'
  post 'admins/createWCookies'
  patch 'admins/update'
  get 'admins/delete'
  post 'admins/update'
  post "admins/delete_multiple"
  post "admins/select_multiple"

  get 'cardapios/index'
  patch 'cardapios/edit'
  post 'cardapios/edit'
  patch 'cardapios/update'


  resources :dado_inseridos
  resources :filas
  resources :restaurantes
  resources :admins
  resources :admins, :collection => {:delete_multiple => :post}
  resources :cardapios

  root 'application#hello'
end

app/views/admins/_form.html.erb
<%= form_with(model: admin, local: true) do |form| %>

    <head>
    <style>
    div {
    font-family: arial, sans-serif;
    border-collapse: collapse;
    width: 100%;
    }

    div {
    text-align: center;
    padding: 4px;
    }

    div:nth-child(even) {

    }
    </style>
    </head>  

  <div class="field">
    <%= form.label :login %>
    <%= form.text_field :login, id: :admin_login %>
  </div>

  <div class="field">
    <%= form.label :senha %>
    <%= form.text_field :senha, id: :admin_senha %>
  </div>

  <div class="field">
    <%= form.label :nome %>
    <%= form.text_field :nome, id: :admin_nome %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/admins/confirm.html.erb
<% if  logged_in? %>
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                                              'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <%= yield %>
    </div>




    <div class="center jumbotron">

<h1> Confirme os dados</h1>

<%= form_tag :action => 'createWCookies' do %>
<p>
  <strong>Login:</strong>
  <%= @admin.login %>
</p>

<p>
  <strong>Senha:</strong>
  <%= @admin.senha %>
</p>

<p>
  <strong>Nome:</strong>
  <%= @admin.nome %>
</p>
<p>
  <strong>email:</strong>
  <%= @admin.email %>
</p>

<%= submit_tag "Cadastrar" %>
<% end -%>
<%= link_to 'voltar', controller: "admins", action: "new", id: @admin %>

</div>



    <div class="container">
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>



  </body>
</html>
<% else %>
<h1>Não logado </h1>
<meta http-equiv="refresh" content="0; url=/" /> 

<% end %> 

app/views/admins/edit.html.erb
<% if  logged_in? %>
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                                              'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <%= yield %>
    </div>




    <div class="center jumbotron">
<h1>Editing Admin</h1>





<%= form_for @admin, :url =>{:action => "update", :id =>@admin} do |f| %>
<p>Login: <%= f.text_field 'login' %></p>
<p>Senha: <%= f.text_field 'senha' %></p>
<p>Confirmacao: <%= f.text_field 'senha_confirmation' %></p>
<p>nome: <%= f.text_field 'nome' %></p>
<p>email: <%= f.text_field 'email' %></p>
<%= f.submit "Save changes" %>
<% end %>

<%= link_to 'Show', @admin %> |
<%= link_to 'Back', admins_path %>
</div>



    <div class="container">
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>



  </body>
</html>


<% else %>
<h1>Não logado </h1>
<meta http-equiv="refresh" content="0; url=/" /> 

<% end %> 

app/views/admins/index.html.erb

<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                                              'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <%= yield %>
    </div>

<style>
{
    font-family: "Trebuchet MS", Arial, Helvetica, sans-serif;
    border-collapse: collapse;
    width: 100%;
}

td, th {
    padding: 8px;
    border-bottom: 1px solid #ddd;
}

tr:nth-child(even){background-color: #f2f2f2;}

tr:hover {background-color: #ddd;}

th {
    padding-top: 12px;
    padding-bottom: 12px;
    text-align: left;
    background-color: rgb(34, 34, 34);
    color: white;
}
</style>


<div class="center jumbotron">
<h1>Administradores</h1>
<h3 >Para deletar administradores, selecionar os registros e apertar o botão deletar</h3>
<table style="width:100%">  
  <thead>
    <tr>
      <th style="text-align:center;">Login</th>
      <th style="text-align:center;">Nome</th>
      <th colspan="3"></th>
    </tr>
  </thead>


  <% if logged_in? %>
  <tbody>
    <p><%= flash[:error] %></p> 
    <%= form_tag :action => 'select_multiple' do %>
    <% for admin in @admins %>
      <tr>
        <td><%= admin.login %></td>
        <td><%= admin.nome %></td>
        <td><%= link_to 'Mais detalhes', admin %></td>
        <td><%=check_box_tag "admin_ids[]", admin.id%></td>

      
      </tr>
    <% end %>
    <p><%= submit_tag "Deletar admin(s)" %></p>
  </tbody>
</table>
<br>

<% end %>
<%= link_to 'New Admin', new_admin_path %>
</div>
<% else %>
<h1>Não logado </h1>
<meta http-equiv="refresh" content="0; url=/" /> 

<% end %> 



</div>



    <div class="container">
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>



  </body>
</html>

app/views/admins/new.html.erb
<% if logged_in? %>
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                                              'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <%= yield %>
    </div>


<style>
input[type=text], select {
    text-align: center;
    width: 50%;
    padding: 6px 10px;
    margin: 1px 0;
    border: 1px solid #ccc;
    border-radius: 4px;

}

input[type=submit] {
    width: 10%;
    background-color: rgb(34, 34, 34);
    color: white;
    padding: 6px 10px;
    margin: 8px 0;
    border: none;
    border-radius: 4px;
    cursor: pointer;
}

div {
    border-radius: 5px;
    background-color: ;
    padding: 20px;
}
</style>

    <div class="center jumbotron">

<% if not flash[:error].nil? %>
<p><%= flash[:error] %></p> 
<%end%>	


<h1>Novo administrador</h1>
<h2> Todos os campos são obrigatórios.</h2>
<h2> O Login tem que ser único.</h2>

<%= form_tag :action => 'createCookie' do %>
<p><label for ="admin_login"> Login</label>
<%= text_field :admin, :login %></p>
<p><label for ="admin_senha"> Senha</label>
<%= text_field :admin, :senha %>
<p><label for ="admin_senha_confirmation"> Confirme a senha</label>
<%= text_field :admin, :senha_confirmation %></p>
<p><label for ="admin_nome"> Nome</label>
<%= text_field :admin, :nome %>
<p><label for ="email"> Email</label>
<%= text_field :admin, :email %>

<br>
<%= submit_tag "Criar" %>
<% end -%>
<%= link_to 'Voltar para lista de administradores', admins_path %>

</div>



    <div class="container">
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>



  </body>
</html>


<% else %>

<h1>Não logado </h1>
<meta http-equiv="refresh" content="0; url=/" /> 

<% end %> 

app/views/admins/select_multiple.html.erb
<% if logged_in? %>
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                                              'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <%= yield %>
    </div>




    <div class="center jumbotron">

<h1>Admins</h1>
<table>
  <thead>
    <tr>
      <th>Login</th>
      <th>Nome</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>


  <h2> Tela de confirmação de exclusão</h2>
  <h2>Selecione os Admins que você realmente deseja excluir</h2>
  <tbody>
    <%= form_tag :action => 'delete_multiple', :url => 'select_multiple_admin_path' do %>
    <% for admin in @admins %>
      <tr>
        <td><%= admin.login %></td>
        <td><%= admin.nome %></td>
        <td><%= admin.email %></td>
        
        <td><%=check_box_tag "admin_ids[]", admin.id%></td>

      
      </tr>
    <% end %>
    <p><label for ="admin_senha"> Confirme sua senha</label></p>
    <%= text_field :admin, :senha %></p>
    <%= submit_tag  "Deleta administradores marcados" %>
  </tbody>
</table>
<br>

<% end %>

<%= link_to 'Voltar para home', controller: "admins", action: "index" %>
</div>



    <div class="container">
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>



  </body>
</html>


<% else %>
<h1>Não logado </h1>
<meta http-equiv="refresh" content="0; url=/" /> 

<% end %> 

app/views/admins/show.html.erb
<% if logged_in? %>

<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                                              'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <%= yield %>
    </div>




    <div class="center jumbotron">

<p>
  <strong>Login:</strong>
  <%= @admin.login %>
</p>

<p>
  <strong>Nome:</strong>
  <%= @admin.nome %>
</p>

<p>
  <strong>Email:</strong>
  <%= @admin.email %>
</p>

<%= link_to 'Editar', edit_admin_path(@admin) %> |
<%= link_to 'Voltar', admins_path %>

</div>



    <div class="container">
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>



  </body>
</html>


<% else %>
<h1>Não logado </h1>
<meta http-equiv="refresh" content="0; url=/" /> 

<% end %> 