config/routes.rb
Rails.application.routes.draw do

  get 'cardapios/new'

  get 'cardapios/index'

  get 'cardapios/edit'

  get 'restaurantes/index'
  post 'restaurantes/create'
  patch 'restaurantes/update'
  post 'restaurantes/update'
  get 'restaurantes/delete'
  get 'restaurantes/confirm'
  get 'restaurantes/data'
  get  'restaurantes/layout_central'
  get 'restaurantes/layout_fisica'
  get 'restaurantes/img_reserva'

  get 'dado_inseridos/delete'
  get 'dado_inseridos/create_url'
  get 'sessions/new'

  get 'estima_fila/update'


  root 'static_pages#home'
  get  '/help',    to: 'static_pages#help'
  get  '/about',   to: 'static_pages#about'
  get  '/contact', to: 'static_pages#contact'

  get 'static_pages/novo_restaurante'

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  get 'sessions/new'

  get 'pagina_admin/admin'
  get 'admins/index'
  post 'admins/create'
  post 'admins/createCookie'
  post 'admins/createWCookies'
  patch 'admins/update'
  get 'admins/delete'
  post 'admins/update'
  post "admins/delete_multiple"
  post "admins/select_multiple"

  get 'cardapios/index'
  patch 'cardapios/edit'
  post 'cardapios/edit'
  patch 'cardapios/update'


  resources :dado_inseridos
  resources :filas
  resources :restaurantes
  resources :admins
  resources :admins, :collection => {:delete_multiple => :post}
  resources :cardapios

  root 'application#hello'
end

app/models/fila.rb
class Fila < ApplicationRecord
end

app/controllers/filas_controller.rb
class FilasController < ApplicationController
  before_action :set_fila, only: [:show, :edit, :update, :destroy]

  # GET /filas
  # GET /filas.json
  def index
    @filas = Fila.all
  end

  # GET /filas/1
  # GET /filas/1.json
  def show
  end

  # GET /filas/new
  def new
    @fila = Fila.new
  end

  # GET /filas/1/edit
  def edit
  end

  # POST /filas
  # POST /filas.json
  def create
    @fila = Fila.new(fila_params)

    respond_to do |format|
      if @fila.save
        format.html { redirect_to @fila, notice: 'Fila was successfully created.' }
        format.json { render :show, status: :created, location: @fila }
      else
        format.html { render :new }
        format.json { render json: @fila.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /filas/1
  # PATCH/PUT /filas/1.json
  def update
    respond_to do |format|
      if @fila.update(fila_params)
        format.html { redirect_to @fila, notice: 'Fila was successfully updated.' }
        format.json { render :show, status: :ok, location: @fila }
      else
        format.html { render :edit }
        format.json { render json: @fila.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /filas/1
  # DELETE /filas/1.json
  def destroy
    @fila.destroy
    respond_to do |format|
      format.html { redirect_to filas_url, notice: 'Fila was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_fila
      @fila = Fila.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def fila_params
      params.require(:fila).permit(:estado_fila, :id_restaurante)
    end
end

app/helpers/filas_helper.rb
module FilasHelper
end

app/views/filas/_form.html.erb
<%= form_with(model: fila, local: true) do |form| %>
  <% if fila.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(fila.errors.count, "error") %> prohibited this fila from being saved:</h2>

      <ul>
      <% fila.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :estado_fila %>
    <%= form.number_field :estado_fila, id: :fila_estado_fila %>
  </div>

  <div class="field">
    <%= form.label :id_restaurante %>
    <%= form.number_field :id_restaurante, id: :fila_id_restaurante %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/filas/edit.html.erb
<h1>Editing Fila</h1>

<%= render 'form', fila: @fila %>

<%= link_to 'Show', @fila %> |
<%= link_to 'Back', filas_path %>

app/views/filas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Filas</h1>

<table>
  <thead>
    <tr>
      <th>Estado fila</th>
      <th>Id restaurante</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @filas.each do |fila| %>
      <tr>
        <td><%= fila.estado_fila %></td>
        <td><%= fila.id_restaurante %></td>
        <td><%= link_to 'Show', fila %></td>
        <td><%= link_to 'Edit', edit_fila_path(fila) %></td>
        <td><%= link_to 'Destroy', fila, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Fila', new_fila_path %>

app/views/filas/new.html.erb
<h1>New Fila</h1>

<%= render 'form', fila: @fila %>

<%= link_to 'Back', filas_path %>

app/views/filas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Estado fila:</strong>
  <%= @fila.estado_fila %>
</p>

<p>
  <strong>Id restaurante:</strong>
  <%= @fila.id_restaurante %>
</p>

<%= link_to 'Edit', edit_fila_path(@fila) %> |
<%= link_to 'Back', filas_path %>