config/routes.rb
Rails.application.routes.draw do

  get 'cardapios/new'

  get 'cardapios/index'

  get 'cardapios/edit'

  get 'restaurantes/index'
  post 'restaurantes/create'
  patch 'restaurantes/update'
  post 'restaurantes/update'
  get 'restaurantes/delete'
  get 'restaurantes/confirm'
  get 'restaurantes/data'
  get  'restaurantes/layout_central'
  get 'restaurantes/layout_fisica'
  get 'restaurantes/img_reserva'

  get 'dado_inseridos/delete'
  get 'dado_inseridos/create_url'
  get 'sessions/new'

  get 'estima_fila/update'


  root 'static_pages#home'
  get  '/help',    to: 'static_pages#help'
  get  '/about',   to: 'static_pages#about'
  get  '/contact', to: 'static_pages#contact'

  get 'static_pages/novo_restaurante'

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  get 'sessions/new'

  get 'pagina_admin/admin'
  get 'admins/index'
  post 'admins/create'
  post 'admins/createCookie'
  post 'admins/createWCookies'
  patch 'admins/update'
  get 'admins/delete'
  post 'admins/update'
  post "admins/delete_multiple"
  post "admins/select_multiple"

  get 'cardapios/index'
  patch 'cardapios/edit'
  post 'cardapios/edit'
  patch 'cardapios/update'


  resources :dado_inseridos
  resources :filas
  resources :restaurantes
  resources :admins
  resources :admins, :collection => {:delete_multiple => :post}
  resources :cardapios

  root 'application#hello'
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    Trabalho para a disciplina PMR3304-Sistemas de Informação. Engenharia Mecatrônica, Escola Politécnica - USP
  </small>
  <nav>
    <ul class="nav navbar-nav navbar-right">
      <li><%= link_to "Sobre",   about_path %></li>
      <li><%= link_to "Contato", contact_path %></li>
      <li><a href="http://www.poli.usp.br//">Poli</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "bandecoapp", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Ajuda", help_path %></li>
        
        <li class = "dropdown">
          <p class="dropdown-toggle" data-toggle="dropdown" style="color:white;">
          Administradores <b class="caret"></b></p>
          <ul class="dropdown-menu" >
        <% if logged_in? %>
          <li><%= link_to "Admins",admins_path %></li>
          <li><%= link_to "Restaurantes",restaurantes_path %></li>
          <li><%= link_to "Cardápios",cardapios_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu2">
              <li><%= link_to "Perfil", current_admin %></li>

              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: :delete %>
              </li>
            </ul>
          </li>
        </ul>
      </li>

        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
        
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BandecoApp</title>




  <body>
  <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
    <%= yield %>
  </body>




  
</html>
